name: Shape Operator
description: 'Thoughts on physics, math, and computers.'
url: http://www.shapeoperator.com
permalink: pretty
excerpt_separator: <!--more-->
redirects: yes

kramdown:
  input: GFM
