name: Squishy Thinking
description: 'Mollusk-like thoughts on physics, math, and computers.'
url: http://squishythinking.com
permalink: pretty
excerpt_separator: <!--more-->
redirects: yes

kramdown:
  input: GFM
